### ISSUE TITLE
Be able to print a list of add-ons that is correct

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#101]
To ensure we can print a proper list of add-ons for door checking, we need to be able to say that an add-on is on a ticket that has been fully paid for.

I noticed not all tickets have the pending / is checkout finalized flags tripped even if their tickets are fully paid up. We'll need a way to backfill them or something similar.

Also, after check-in, a person can add an add-on.

If we don't have a way to clear the list of people who added an add-on but did not pay for it, the list we print will be incorrect. We may want to write a command that clears a specific set of add-on tickets.

**Comment by CarlNelson** [comment]
A view that shows all the add-ons

Select an add-on > go to view of a list of attendees registered for that add-on who have paid for that add-on

List should include
- Total Lead / Follow Ratio & Add-on Tickets sold
- Name of Attendee
- Role (if required by add-on)

**Comment by NicoleZuckerman** [comment]
Landed the addon view part. 
Still need to figure out what's up with some of the addons that weren't paid but didn't look like they should be removed.  When that is done, we can add the management command (also landed already) to our cron.

**Comment by CarlNelson** [comment]
I double checked a few, in prod a number of the ones you called out from your local were paid in production.

**Comment by CarlNelson** [comment]
Landed.
