### ISSUE TITLE
UI for Access Codes

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#11]
Most of the back end code is done, need to finish up the UI and script.

- [x] @NicoleZuckerman to add CTA to end of checkout flow for $0.00 tickets to move on to profile
- [x] @NorthIsUp to run script
- [x] @NicoleZuckerman case insensitive codes __iexact (nicole knows what this means), ticket_tier.best_tier function (access code should have iexact ~line 100),

**Comment by NicoleZuckerman** [comment]
CTA added, codes made case insensitive.
Fixed two bugs I found along the way.
