### ISSUE TITLE
Add Edit Survey Link to Profile Page

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#19]
Was breaking the profile page when it was present.

**Comment by NicoleZuckerman** [comment]
@CarlNelson I created a branch edit_survey_link with this change on it-- can you test on yours?  I want to make sure it works on other people's local env before I push to prod.

**Comment by NicoleZuckerman** [comment]
Carl tested, confirmed it worked.  Closing.
