### ISSUE TITLE
Improve Add-Ons Experience after initial purchase

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#22]

**Comment by CarlNelson** [comment]
**User Flow**
Click on a link from Paid ticket on Profile Page
Go to Add-Ons page
Select new Add-Ons
Go to checkout page
Click Pay Now (no subscription option)

Add-Ons are added to the ticket.

**Comment by NicoleZuckerman** [comment]
In branch more_addons, for review

**Comment by CarlNelson** [comment]
@NorthIsUp to review Nicole's PR

**Comment by NorthIsUp** [comment]
#43

**Comment by CarlNelson** [comment]
This shouldn't be closed until these missing features are implemented.

[ ] Does not show a call to action on the Profile page ticket to 'Purchase Add-Ons'
[ ] Should show a Total Amount - Amount Paid with a Your Total on the check-out page.

> I can't since I can't seem to get @NicoleZuckerman's original work up and running to take a screenshot of what it should look like but please look at this [commit](https://github.com/SugarPushCode/FocusOnLindy/commit/9a64f86364405448a542fd8335d000ce733cea92) and the markup changes for ticket_card.html and profile.html in that commit. Those are the updates that got missed in your re-write and how they should be displayed.

**Comment by NorthIsUp** [comment]
I think we can close this.
