### ISSUE TITLE
Display Add-Ons for a Ticket in Admin

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#23]
![image](https://cloud.githubusercontent.com/assets/835698/16641566/ca19120a-43b6-11e6-9b18-ef4d40f1761a.png)

We should display what add ons a ticket has associated with it so Jaya can look up an individual user's ticket and see what pass + addons they have selected.

**Comment by CarlNelson** [comment]
Other information we should show on a ticket probably:
- Ticket Total Cost
- Amount Received
- Dance Role
- Dance Role for Selected Add-Ons where applicable

**Comment by NicoleZuckerman** [comment]
Fix pushed to branch ticket_admin_new_fields
@CarlNelson take a look.

**Comment by NicoleZuckerman** [comment]
Carl looked, said it was fine.  Merging.
