### ISSUE TITLE
Sort Add-Ons by Schedule Order

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#25]
Sort by time per category

**Comment by NicoleZuckerman** [comment]
I assume this means sort by the FIRST timeslot for an addon... as some of the add ons have multiple timeslots. Yes?

**Comment by CarlNelson** [comment]
Yep

**Comment by CarlNelson** [comment]
Will not fix this year. Will think about sort order for 2017.
