### ISSUE TITLE
Remove Leader/Follow Question from Dance Pass Survey

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#26]

**Comment by NorthIsUp** [comment]
Unless this is a huge problem I recommend we do this for next year, I don't wan't to risk a survey migration causing more harm than good.

**Comment by CarlNelson** [comment]
Cool with me. I can let Jaya now.

**Comment by NicoleZuckerman** [comment]
Added "Prefer not to choose" value for dance pass, no migration necessary.  Class pass still only has lead/follow option on form.
