### ISSUE TITLE
Access Code Dance Passes Aren't Removed Click Change Pass

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#27]
![image](https://cloud.githubusercontent.com/assets/835698/16694065/1dadac46-44ed-11e6-8c8b-3972b49d5c07.png)

**Comment by CarlNelson** [comment]
Should be fixed before we close #11

**Comment by NorthIsUp** [comment]
I'm actively working on this.

**Comment by NorthIsUp** [comment]
Ref #11

**Comment by CarlNelson** [comment]
Yep, why I assigned it to you :)

**Comment by CarlNelson** [comment]
Carl to review
