### ISSUE TITLE
Cookie for Access Codes persisting after log out / across users

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#28]
We need to change this before Jaya sends out more access codes.

Rolls up to #11

**Comment by CarlNelson** [comment]
This existed from the beginning of access codes, Nicole noticed it but I forgot to log the bug.

**Comment by NicoleZuckerman** [comment]
@NorthIsUp I'd feel better if you took this one; since you wanted access codes in the cookie in the first place, you probably have ideas about how to handle it.
