### ISSUE TITLE
Tickets that are marked "is paid" should not be marked with "is pending"

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#35]
![image](https://cloud.githubusercontent.com/assets/835698/17459784/eb7f3420-5bfc-11e6-9cdb-c0d949509f89.png)

If a ticket is paid in full the ticket should not be marked as Is Pending as well.

**Comment by NorthIsUp** [comment]
While confusing in the UI this is not actually a bug. They are more like mile markers you pass than a state.

**Comment by CarlNelson** [comment]
So we should change it so that it is not the case. It is confusing and we should consider them separate states.

**Comment by NorthIsUp** [comment]
Since this is part of the technical design and is only annoying in the UI let's mark this as an enhancement for the 2017 refactor.
