### ISSUE TITLE
PayPal Reporting & Admin Reporting Still Mismatched

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#42]
Still determining all of the causes.

**Contributing issues:**
- Double counting for IPNs that weren't flagged #30 
- Counting failed subscription IPNs as money paid #40

**Comment by CarlNelson** [comment]
Nicole ran some manual transaction comparison between exported PayPal transaction history and our databases transaction history. Caught some unflagged double counting issues.

**Comment by jayagamble** [comment]
Current status: 
Paypal reports receiving $548.90 more then is reported on the admin for received net revenue. One contributing cause is I have two manual payments from Pamela Langston for net amounts: $72.52 (Unique Transaction ID # 5YN43762C7695523X) and $75 (Unique Transaction ID # 39784506B2914860N).  These amounts need to be linked to Pamela's registration.

That brings the total unknown discrepancy amount down to $401.38. We need to find the cause for this unreported amount in our database.

**Comment by jayagamble** [comment]
Reports are all set now except for manual payments (just Pamela at the moment) and $1.80 unaccounted for. Could this be because when I send someone a full refund paypal keeps $0.30?

**Comment by CarlNelson** [comment]
How many full refunds have you made so far?

If it is 6, it is most likely that is the case.

**Comment by jayagamble** [comment]
Net received is now incorrect again. Thoughts:
1. Cancelation fees are not showing up in net received even though this is in fact money received. I believe the total here is $650.90 to date. Perhaps the net received calculation can include all passes regardless of cancelation status in order to reflect actual amount received.
2.  There is likely a small amount from the $.30 fees paypal keeps but I haven't calculated the exact amount.
3. The remaining amount is around $190 that we have received but is not accounted for in the reports.

**Comment by CarlNelson** [comment]
1. That is currently the case, they're excluded from the report to not show ticket counts but that also currently impacts what is net received in that report at the moment.

**Comment by jayagamble** [comment]
1. OK, not a problem if my calculation is accurate and I can use it to manually double check the data of reported net received and actual net received but if my calculation is incorrect I will not be able to determine why.
3. I found one item that changes the 190 to -85. I'll keep looking to determine any other special issues.

**Comment by CarlNelson** [comment]
Okay, I'm pushing a fix that removes canceled tickets from the sold ticket counts but not the money we keep from them.
