### ISSUE TITLE
Pricing Table is returning the incorrect info for some reason

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#45]
Just noticed the pricing table on the registration page shows the following. Obviously "next tier" is out of place now. But the real issue is the displayed door prices are incorrect. I don't see in the admin where door price is even a tier listed so I can't edit it myself. Door prices are supposed to be 355 and 225. 

![image](https://cloud.githubusercontent.com/assets/835698/18154924/a164fd0a-6fbd-11e6-95f9-4cf4a0d4faae.png)

**Comment by NicoleZuckerman** [comment]
I added the At The Door price, not available until 12/26.  No access code needed.
