### ISSUE TITLE
Handle Subscriptions that Lapsed

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#48]
There are a number of subscriptions which lapsed leaving tickets unpaid.

As a user, when my subscription lapses and my ticket is not fully paid I want to receive an email telling me to restart the payment process.

As a Jaya, I want to see how many unpaid tickets have lapsed subscriptions.

**Comment by CarlNelson** [comment]
As a user, I should be able to start a new subscription or pay my balance in full if my subscription failed and ended the subscription transaction.

**UI**
Show Payment buttons on Ticket on profile page when subscr_eot IPN has been received from PayPal and there is still a balance on the ticket and it is not abandoned or cancelled.

**Comment by NicoleZuckerman** [comment]
In a PR right now for Adam's review
