### ISSUE TITLE
Contact Form on Website

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#49]
Create a contact form on the website for people to reach out to Michael / Jaya.

**Comment by CarlNelson** [comment]
Waiting on confirmation of what email to send the form to.

**Comment by jayagamble** [comment]
@CarlNelson just now seeing you need confirmation on email. sorry, had no idea! please have emails sent to lindyfocus@gmail.com

**Comment by jayagamble** [comment]
also, here is the lindy focus phone number that could be listed on the contact page as well (747) 333-6287

**Comment by CarlNelson** [comment]
Done and done.
