### ISSUE TITLE
Pay over time broken

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#52]
We had a single report of a Pay Over Time issue from a user being unable to transact.

This was the error they saw.

![image](https://cloud.githubusercontent.com/assets/835698/18963265/0cf3b6d4-8629-11e6-8841-36ea90b840f4.png)

Was able to reproduce in production but may not have been able to catch in staging since it wouldn't have been the same PayPal transaction.

We haven't seen any Pay Over Time transactions come through since Sept 10, so it may be connected to the lapsed subscription changes.

Possible causes checklist
- [x] client id and secret are correct in heroku

**Comment by NorthIsUp** [comment]
looking into this now

**Comment by CarlNelson** [comment]
Hide the button for now.

**Comment by CarlNelson** [comment]
@NorthIsUp to look at this in the developer console for PayPal

**Comment by NorthIsUp** [comment]
The pay over time button is hidden until I can figure it out, this is done via the PAYPAL_DISABLE_SUBSCRIPTION env var.

**Comment by CarlNelson** [comment]
Any update on this from your investigations in PayPal @NorthIsUp?

**Comment by NorthIsUp** [comment]
No new information :(

**Comment by CarlNelson** [comment]
Will not fix. Push to 2017.
