### ISSUE TITLE
Audition Check-In System

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#57]
Use Cases
- Look up an attendee
- Assign a bib to an attendee
- Confirm attendee in correct group / heat
- Re-assign bib number or heat or group to an attendee (think no shows, etc.)
- Backups / double checks for each heat / group

**Comment by CarlNelson** [comment]
Carl to design the checkin flow.

**Comment by CarlNelson** [comment]
[Audition Check-In Flow](https://invis.io/5B9J8V64T)

**Comment by CarlNelson** [comment]
They have traditionally used BIB numbers to line people up. We hadn't anticipated BIB numbers having to be in order. This may not actually be a problem since traditionally in audition check-in each heat has it's own stack of BIB numbers.

They also have traditionally adjusted heats on the fly in case people don't show up for an audition group. This will throw off our placement app unless we have someone re-assigning people from heat to heat manually as they adjust on the fly.

We prolly want to figure out a better way to quickly adjust what BIB numbers are in a heat.

**Comment by NicoleZuckerman** [comment]
Merged.
