### ISSUE TITLE
Make "Cancelled" status adjust capacity and payments

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#66]
Tickets that are cancelled are still counted in capacity & total revenue/pending reports

**Comment by CarlNelson** [comment]
Make sure to account for PayPal keeping some of the money.

**Comment by NicoleZuckerman** [comment]
Sorry, but I think I need more information about this:
When a ticket is cancelled, do you want to delete any add ons associated with them (so quantity is returned to the pool)?  As in, there would no longer be a record of them having been attached to this ticket?
Should cancelled tickets appear in the individual sales report?
Note: We should already have accurate dollar-amount reporting that accounts for cancelled tickets (if Jaya as refunded them)--what makes you think we haven't?
And when you say "account for Paypal keeping some money", what do you mean?  between "amount paid" and "mc_fee" we should have all the info.  
Do I need to change the "amount due" on a cancelled ticket to reflect that it doesn't owe money?  If so, how much? Jaya independently decides how much of a "reshelving" fee to keep, and there isn't a good way to account for that $.

**Comment by CarlNelson** [comment]
Yes we should null / remove any add ons associated with it so capacity is returned to the pool.

Cancelled tickets should probably not show up in the individual sales report. I think it's mostly for amount due that needs to be reflected accurately. I'll check with Jaya but I think it's a set reshelving percentage, I will double check.
