### ISSUE TITLE
Add Contest Add-Ons

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#73]
MG reached out saying they'll have contests this year.
- solo jazz *
- strictly bal *
- strictly blues *
- strictly lindy *

(\* probably NOT these names)

For partnered contest add-ons, can we capture a partners name as part of the add-on similar to how we capture role today?

**Comment by NorthIsUp** [comment]
-1 on doing partner name capture until registration and auditions are done.

**Comment by CarlNelson** [comment]
I'll email Michael to see when he needs this by.

**Comment by CarlNelson** [comment]
November 23rd is when he wants to put them on sale.

**Comment by CarlNelson** [comment]
Are these basically ready to go @NorthIsUp? I saw you had a branch about this.

What needs to be done to take it over the line? The 23rd will sneak up quickly.

**Comment by CarlNelson** [comment]
Done in #89
