### ISSUE TITLE
Breakfast Add-On

### ISSUE THREAD

**Issue by jayagamble** [SugarPushCode/FocusOnLindy#85]
Description for breakfast add-on shows up under registration but not under the website add-on tab. 

New Year's Eve Add-Ons: Breakfast used to be the default top of the list add-on for after you select a pass but now Balboa is. Breakfast should be first to guide people to select this item which they may not even know about otherwise.

**Comment by CarlNelson** [comment]
This may get pushed down the list until we get audition and check-in working.

**Comment by jayagamble** [comment]
No problem. It's not relevant to a successful event but worth noting for
future fixes.

**Comment by CarlNelson** [comment]
Fixed.
