### ISSUE TITLE
Subscription + Comp AddOns Incorrect Balance

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#90]
Mimi's [ticket](https://register.lindyfocus.com/admin/ticket/ticket/122/change/) is showing as a failed subscription when it isn't.

The price for comp add-ons is computed incorrectly (double what should be owed).

![image](https://cloud.githubusercontent.com/assets/835698/20652250/a67432b6-b4aa-11e6-9a8f-7066c9336ef5.png)

**Comment by NorthIsUp** [comment]
fixed by 208aeed
