### ISSUE TITLE
A la Carte Dance Passes

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#93]
Find pricing etc here http://www.lindyfocus.com/registration-2/

**Comment by CarlNelson** [comment]
Jaya doesn't mind if users who sign up for a la carte passes register for add-ons that aren't on the days in which they bought a dance night for.

So we can skip add-on requirements and just require the a la carte dance pass to have at least one day pass add-on.

@NorthIsUp

**Comment by NorthIsUp** [comment]
this is basically done. we just need copy to make it evident what is going on

**Comment by CarlNelson** [comment]
Landed.
