### ISSUE TITLE
Expanded menu items incomprehensible

### ISSUE THREAD

**Issue by olingern** [SugarPushCode/FocusOnLindy#96]
I stumbled across this a while ago. Nice job on the project, all.

Though, I won't be able to make it - I still clicked through the email sent out pinging people to complete their registration. I noticed the menu has some issues in Chrome. Below is "Registration" expanded.

<img width="800" alt="screen shot 2016-12-03 at 11 44 01 pm" src="https://cloud.githubusercontent.com/assets/1470297/20864147/75eae646-b9b2-11e6-80f5-244888199d42.png">

It should probably look more like this (different menu item expanded):

<img width="764" alt="screen shot 2016-12-03 at 11 23 45 pm" src="https://cloud.githubusercontent.com/assets/1470297/20864149/8ede3c20-b9b2-11e6-92ee-77448fb9318d.png">

I would make a PR, but it looks like this CSS file is hosted on SquareSpace. 

So, here's the CSS to fix (untested!).

``` css
.info-page-layout-poster #main-navigation ul.folder-child {
    margin: 0 1em 0 0;
    padding: 0 10px 0 15px;
    background-color: #000;
    position: relative;
}
```

``` css 
.info-page-layout-poster #main-navigation .folder.dropdown-open {
  background: #000;
}
```

Cheers.

**Comment by NorthIsUp** [comment]
First real bug report! Thanks, we'll fix this.

**Comment by CarlNelson** [comment]
Fixed.
